version: '3.8'

services:
  catalog-service:
    build: ./backend/catalog-service
    ports:
      - "3001:3001"
    env_file:
      - ./backend/catalog-service/.env

  personalization-service:
    build: ./backend/personalization-service
    ports:
      - "3002:3002"
    env_file:
      - ./backend/personalization-service/.env

  order-service:
    build: ./backend/order-service
    ports:
      - "3003:3003"
    env_file:
      - ./backend/order-service/.env

  admin-service:
    build: ./backend/admin-service
    ports:
      - "3004:3004"
    env_file:
      - ./backend/admin-service/.env

  flutter-frontend:
    build: .
    ports:
      - "8080:8080"
